require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommunityLevelsController do

  # This should return the minimal set of attributes required to create a valid
  # CommunityLevel. As you add validations to CommunityLevel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommunityLevelsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all community_levels as @community_levels" do
      community_level = CommunityLevel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:community_levels).should eq([community_level])
    end
  end

  describe "GET show" do
    it "assigns the requested community_level as @community_level" do
      community_level = CommunityLevel.create! valid_attributes
      get :show, {:id => community_level.to_param}, valid_session
      assigns(:community_level).should eq(community_level)
    end
  end

  describe "GET new" do
    it "assigns a new community_level as @community_level" do
      get :new, {}, valid_session
      assigns(:community_level).should be_a_new(CommunityLevel)
    end
  end

  describe "GET edit" do
    it "assigns the requested community_level as @community_level" do
      community_level = CommunityLevel.create! valid_attributes
      get :edit, {:id => community_level.to_param}, valid_session
      assigns(:community_level).should eq(community_level)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommunityLevel" do
        expect {
          post :create, {:community_level => valid_attributes}, valid_session
        }.to change(CommunityLevel, :count).by(1)
      end

      it "assigns a newly created community_level as @community_level" do
        post :create, {:community_level => valid_attributes}, valid_session
        assigns(:community_level).should be_a(CommunityLevel)
        assigns(:community_level).should be_persisted
      end

      it "redirects to the created community_level" do
        post :create, {:community_level => valid_attributes}, valid_session
        response.should redirect_to(CommunityLevel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved community_level as @community_level" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityLevel.any_instance.stub(:save).and_return(false)
        post :create, {:community_level => { "name" => "invalid value" }}, valid_session
        assigns(:community_level).should be_a_new(CommunityLevel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityLevel.any_instance.stub(:save).and_return(false)
        post :create, {:community_level => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested community_level" do
        community_level = CommunityLevel.create! valid_attributes
        # Assuming there are no other community_levels in the database, this
        # specifies that the CommunityLevel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommunityLevel.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => community_level.to_param, :community_level => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested community_level as @community_level" do
        community_level = CommunityLevel.create! valid_attributes
        put :update, {:id => community_level.to_param, :community_level => valid_attributes}, valid_session
        assigns(:community_level).should eq(community_level)
      end

      it "redirects to the community_level" do
        community_level = CommunityLevel.create! valid_attributes
        put :update, {:id => community_level.to_param, :community_level => valid_attributes}, valid_session
        response.should redirect_to(community_level)
      end
    end

    describe "with invalid params" do
      it "assigns the community_level as @community_level" do
        community_level = CommunityLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => community_level.to_param, :community_level => { "name" => "invalid value" }}, valid_session
        assigns(:community_level).should eq(community_level)
      end

      it "re-renders the 'edit' template" do
        community_level = CommunityLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => community_level.to_param, :community_level => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested community_level" do
      community_level = CommunityLevel.create! valid_attributes
      expect {
        delete :destroy, {:id => community_level.to_param}, valid_session
      }.to change(CommunityLevel, :count).by(-1)
    end

    it "redirects to the community_levels list" do
      community_level = CommunityLevel.create! valid_attributes
      delete :destroy, {:id => community_level.to_param}, valid_session
      response.should redirect_to(community_levels_url)
    end
  end

end
