require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaluksController do

  # This should return the minimal set of attributes required to create a valid
  # Taluk. As you add validations to Taluk, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "district" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaluksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all taluks as @taluks" do
      taluk = Taluk.create! valid_attributes
      get :index, {}, valid_session
      assigns(:taluks).should eq([taluk])
    end
  end

  describe "GET show" do
    it "assigns the requested taluk as @taluk" do
      taluk = Taluk.create! valid_attributes
      get :show, {:id => taluk.to_param}, valid_session
      assigns(:taluk).should eq(taluk)
    end
  end

  describe "GET new" do
    it "assigns a new taluk as @taluk" do
      get :new, {}, valid_session
      assigns(:taluk).should be_a_new(Taluk)
    end
  end

  describe "GET edit" do
    it "assigns the requested taluk as @taluk" do
      taluk = Taluk.create! valid_attributes
      get :edit, {:id => taluk.to_param}, valid_session
      assigns(:taluk).should eq(taluk)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Taluk" do
        expect {
          post :create, {:taluk => valid_attributes}, valid_session
        }.to change(Taluk, :count).by(1)
      end

      it "assigns a newly created taluk as @taluk" do
        post :create, {:taluk => valid_attributes}, valid_session
        assigns(:taluk).should be_a(Taluk)
        assigns(:taluk).should be_persisted
      end

      it "redirects to the created taluk" do
        post :create, {:taluk => valid_attributes}, valid_session
        response.should redirect_to(Taluk.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taluk as @taluk" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taluk.any_instance.stub(:save).and_return(false)
        post :create, {:taluk => { "district" => "invalid value" }}, valid_session
        assigns(:taluk).should be_a_new(Taluk)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taluk.any_instance.stub(:save).and_return(false)
        post :create, {:taluk => { "district" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taluk" do
        taluk = Taluk.create! valid_attributes
        # Assuming there are no other taluks in the database, this
        # specifies that the Taluk created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Taluk.any_instance.should_receive(:update_attributes).with({ "district" => "" })
        put :update, {:id => taluk.to_param, :taluk => { "district" => "" }}, valid_session
      end

      it "assigns the requested taluk as @taluk" do
        taluk = Taluk.create! valid_attributes
        put :update, {:id => taluk.to_param, :taluk => valid_attributes}, valid_session
        assigns(:taluk).should eq(taluk)
      end

      it "redirects to the taluk" do
        taluk = Taluk.create! valid_attributes
        put :update, {:id => taluk.to_param, :taluk => valid_attributes}, valid_session
        response.should redirect_to(taluk)
      end
    end

    describe "with invalid params" do
      it "assigns the taluk as @taluk" do
        taluk = Taluk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taluk.any_instance.stub(:save).and_return(false)
        put :update, {:id => taluk.to_param, :taluk => { "district" => "invalid value" }}, valid_session
        assigns(:taluk).should eq(taluk)
      end

      it "re-renders the 'edit' template" do
        taluk = Taluk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taluk.any_instance.stub(:save).and_return(false)
        put :update, {:id => taluk.to_param, :taluk => { "district" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taluk" do
      taluk = Taluk.create! valid_attributes
      expect {
        delete :destroy, {:id => taluk.to_param}, valid_session
      }.to change(Taluk, :count).by(-1)
    end

    it "redirects to the taluks list" do
      taluk = Taluk.create! valid_attributes
      delete :destroy, {:id => taluk.to_param}, valid_session
      response.should redirect_to(taluks_url)
    end
  end

end
